plugins:
  topic_list_previews_enabled:
    default: true
    client: true
  topic_list_show_like_on_current_users_posts:
    default: false
    client: true
  topic_list_excerpt_length:
    default: 200
    client: true
  topic_list_excerpt_remove_links:
    default: true
    client: false
